--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    environment: 
      JVM_OPTS: "-Xmx3200m"
      TERM: dumb
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"pom.xml\" }}"
            - v1-dependencies-
      - 
        run: "mvn validate"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"pom.xml\" }}"
          paths: 
            - ~/.m2
      - 
        run: "mvn compile"
    test: 
      - 
        run: "mvn test"
      - 
        store_artifacts: 
          destination: tr1
          path: target/surefire-reports
      - 
        store_test_results: 
          path: target/surefire-reports
    working_directory: ~/repo
version: 2
